### ISSUE TITLE
magit highline line face uses color intended for dark themes in light themes

### ISSUE THREAD

**Issue by lvh** [syl20bnr/spacemacs#11709]
#### Description :octocat:

In light themes, the magit line highlight background is a dark grey, which makes the line illegible.

#### Reproduction guide :beetle:

I haven't been able to isolate this, but here's what reproduces it on my machine:

- Start Emacs with leuven-theme selected
- Open magit-status in a Git-controlled file with <kbd>SPC g s</kbd>
- Move cursor to e.g. a commit

*Observed behaviour:* :eyes: :broken_heart:
Highlighted line background is gray20.

*Expected behaviour:* :heart: :smile:
Highlighted line background is something light

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(yaml javascript helm auto-completion better-defaults colors themes-megapack emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control python clojure terraform docker)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Extra info

At first I thought this might be related to https://github.com/magit/magit/issues/1922 but that seems way too old to still be relevant.

Partial output from describe-char on an affected line:

```
             position: 171 of 606 (28%), column: 31
            character: t (displayed as t) (codepoint 116, #o164, #x74)
    preferred charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x74
               script: latin
               syntax: w 	which means: word
             category: .:Base, L:Left-to-right (strong), a:ASCII, l:Latin, r:Roman, u:Lowercase
             to input: type "C-x 8 RET 74" or "C-x 8 RET LATIN SMALL LETTER T"
          buffer code: #x74
            file code: #x74 (encoded by coding system utf-8)
              display: by this font (glyph code)
    xft:-CTDB-Fira Code-normal-normal-normal-*-18-*-*-*-m-0-iso10646-1 (#xE9)

Character code properties: customize what to show
  name: LATIN SMALL LETTER T
  general-category: Ll (Letter, Lowercase)
  decomposition: (116) ('t')

There are 2 overlays here:
 From 140 to 210
  evaporate            t
  face                 magit-section-highlight
 From 141 to 209
  before-string        [Show]
  evaporate            t


There are text properties here:
  keymap               [Show]
  magit-section        [Show]
```

The culprit appears to be magit-section-highlight face:

```
Face: magit-section-highlight (sample) (customize this face)

Documentation:
Face for highlighting the current section.

Defined in ‘magit-section.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: grey20
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified

```

(note grey20 background)

That face is defined as follows:

```
(defface magit-section-highlight
  '((((class color) (background light)) :background "grey95")
    (((class color) (background  dark)) :background "grey20"))
  "Face for highlighting the current section."
  :group 'magit-faces)
```

... which makes no sense -- clearly levuen is a light theme. I can reproduce with a number of other light 
```
