### ISSUE TITLE
Font doesn't load properly without updating fontcache

### ISSUE THREAD

**Issue by treymerkley** [syl20bnr/spacemacs#13878]
Hi there!

So I'm trying to use Tamzen as my font, and it worked fairly well until the upgrade to 27.1. When I start Emacs, beit by the client or as a standalone, Emacs loads this font:

```
Documentation:
Basic default face.

Defined in ‘faces.el’.


           Family: Tamzen
          Foundry: KBnP
            Width: normal
           Height: 126
           Weight: normal
            Slant: normal
       Foreground: #655370
DistantForeground: unspecified
       Background: #fbf8ef
        Underline: nil
         Overline: nil
   Strike-through: nil
              Box: nil
          Inverse: nil
          Stipple: nil
             Font: #<font-object -KBnP-Tamzen-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1>
          Fontset: -KBnP-Tamzen-normal-normal-normal-*-14-*-*-*-m-0-fontset-auto2
           Extend: nil
          Inherit: nil
```

What I want is for it to load:
```

Documentation:
Basic default face.

Defined in ‘faces.el’.


           Family: Tamzen
          Foundry: Misc
            Width: normal
           Height: 126
           Weight: normal
            Slant: normal
       Foreground: #655370
DistantForeground: unspecified
       Background: #fbf8ef
        Underline: nil
         Overline: nil
   Strike-through: nil
              Box: nil
          Inverse: nil
          Stipple: nil
             Font: #<font-object -Misc-Tamzen-normal-normal-normal-*-14-*-*-*-c-70-iso10646-1>
          Fontset: -Misc-Tamzen-normal-normal-normal-*-14-*-*-*-c-70-fontset-auto3
           Extend: nil
          Inherit: nil
```
Which it does if I update the fontcache first.

I'm currently setting this by using

```
 (add-hook 'after-make-frame-functions
            (lambda (frame)
              (select-frame frame)
              (set-face-attribute 'default nil :family "Tamzen")))
...
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:background nil :family "Tamzen" :foundry "Misc" :slant normal :weight normal :height 130 :width normal)))))
```

What else should I try?
