### ISSUE TITLE
YAML font lock (syntax highlighting) issues

### ISSUE THREAD

**Issue by eeshugerman** [syl20bnr/spacemacs#14150]
#### Description :octocat:
YAML font lock (syntax highlighting) issues involving quoted strings containing punctuation.

yaml-mode issue: https://github.com/yoshiki/yaml-mode/issues/82

This bug is not present with a vanilla Emacs + yaml-mode install, but is present with a vanilla
Spacemacs + YAML layer install. That said, the bug can be "fixed" by removing a few lines from
`yaml-mode.el` (removing a feature along with it) -- see the issue linked above for details.

#### Reproduction guide :beetle:
- start Emacs
- open the scratch buffer
- paste the following text into the scratch buffer (this is the simplest case I've found)
```yaml
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: 'a.a'
a: a
```
- enable `yaml-mode`

> **NOTE**: the order of the last two steps matters

*Observed behaviour:* :eyes: :broken_heart:
Incorrect font lock on last line

*Expected behaviour:* :heart: :smile:
Correct font lock everywhere

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 812877409)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP

> **NOTE**: The issue is also present with any of...
> - OS: gnu/linux
> - Emacs: 28.0.50
> - Graphic display: nil
> - Completion: Ivy

#### Backtrace :paw_prints:
N/A
