### ISSUE TITLE
Sorting lines in block/region preserving hierarchy

### ISSUE THREAD

**Issue by Antiarchitect** [syl20bnr/spacemacs#14767]
Is there any chance I could sort YAML (and not only) structures properly? `SPC-x-l-s` not doing it (bet it is not supposed to).

In:
```
app-2.xxx:
  ip: '1.1.1.1'
app-1.xxx:
  ip: '8.8.8.8'
```

Desired out:

```
app-1.xxx:
  ip: '8.8.8.8'
app-2.xxx:
  ip: '1.1.1.1'
```

`SPC-x-l-s` Out
```
  ip: '1.1.1.1'
  ip: '8.8.8.8'
app-1.xxx:
app-2.xxx:
```

Maybe there is a way to do it already, but I didn't find it.
